/*
 * Copyright (C) 2020 Matteo Hausner
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

package de.bwravencl.controllerbuddy.input.action;

import de.bwravencl.controllerbuddy.input.Input;
import de.bwravencl.controllerbuddy.input.action.annotation.ActionProperty;
import de.bwravencl.controllerbuddy.input.action.gui.DescriptionEditorBuilder;
import java.lang.constant.Constable;

/// Abstract base class for actions that carry a user-configurable description.
///
/// If a custom description is set, it takes precedence over the default
/// description generated by the action type.
///
/// @param <V> the type of input value this action processes
public abstract class DescribableAction<V extends Constable> implements IAction<V> {

	/// The user-configurable description text, or `null` if none has been set.
	@ActionProperty(icon = "📖", title = "DESCRIPTION_TITLE", description = "DESCRIPTION_DESCRIPTION", editorBuilder = DescriptionEditorBuilder.class, order = 0)
	private String description;

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	/// Returns the raw custom description string, or `null` if none is set.
	///
	/// @return the custom description, or `null`
	public String getDescription() {
		return description;
	}

	/// Returns the custom description if set, otherwise falls back to the default
	/// description.
	///
	/// @param input the current input state
	/// @return the action description
	@Override
	public String getDescription(final Input input) {
		if (!isDescriptionEmpty()) {
			return description;
		}

		return IAction.getDefaultDescription(this);
	}

	/// Returns whether the custom description is empty or unset.
	///
	/// @return `true` if no custom description has been set
	boolean isDescriptionEmpty() {
		return description == null || description.isEmpty();
	}

	/// Sets the custom description for this action.
	///
	/// @param description the description text to set
	public void setDescription(final String description) {
		this.description = description;
	}
}
