name: Build

on:
  push:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19.0.2
      - name: Build
        uses: eskatos/gradle-command-action@v2
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
        with:
          arguments: distZip --info
      - name: Extract Release Variables
        id: extract_release_variables
        shell: bash
        run: |
          echo ::set-output name=tag_name::$(find build/distributions/ControllerBuddy-*.zip -maxdepth 1 -print0 | xargs -0 -I filename basename -s .zip filename | sed s/-windows-x86-64//)
          echo ::set-output name=archive_path::$(find build/distributions/ControllerBuddy-*.zip -maxdepth 1 -print0)
      - name: Tag Commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_release_variables.outputs.tag_name }}
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_release_variables.outputs.tag_name }}
          draft: false
          prerelease: false
          files: ${{ steps.extract_release_variables.outputs.archive_path }}
  linux:
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19.0.2
      - name: Build
        uses: eskatos/gradle-command-action@v2
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
        with:
          arguments: distTar --info
      - name: Extract Release Variables
        id: extract_release_variables
        shell: bash
        run: |
          echo ::set-output name=tag_name::$(find build/distributions/ControllerBuddy-*.tgz -maxdepth 1 -print0 | xargs -0 -I filename basename -s .tgz filename | sed s/-linux-x86-64//)
          echo ::set-output name=archive_path::$(find build/distributions/ControllerBuddy-*.tgz -maxdepth 1 -print0)
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_release_variables.outputs.tag_name }}
          draft: false
          prerelease: false
          files: ${{ steps.extract_release_variables.outputs.archive_path }}
