name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 18.0.1+10
      - name: Build
        uses: eskatos/gradle-command-action@v1
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
        with:
          arguments: distZip --info
      - name: Extract Release Variables
        id: extract_release_variables
        shell: bash
        run: |
          echo ::set-output name=tag_name::$(ls build/distributions/ControllerBuddy-*.zip | xargs -i basename {} .zip)
          echo ::set-output name=zip_path::$(ls build/distributions/ControllerBuddy-*.zip)
      - name: Tag Commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_release_variables.outputs.tag_name }}
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_release_variables.outputs.tag_name }}
          draft: false
          prerelease: false
          files: ${{ steps.extract_release_variables.outputs.zip_path }}
