name: Dependency Update Check

on:
  schedule:
    - cron: '* 18 * * *'

jobs:
  dependencyUpdateCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 18.0.0
      - name: Gradle Update Check
        uses: MeilCli/gradle-update-check-action@v3
        id: gradle_update_check
        with:
          skip_plugin_dependency: true
      - name: SendGrid E-Mail
        uses: raynigon/sendgrid-mail-action@1.0.1
        if: steps.gradle_update_check.outputs.has_maven_update != 'false'
        with:
          sendgrid-token: ${{ secrets.SENDGRID_TOKEN }}
          from: ${{ secrets.MY_EMAIL }}
          to: ${{ secrets.MY_EMAIL }}
          subject: ControllerBuddy - Outdated Dependencies
          text: ${{ steps.gradle_update_check.outputs.maven_update_text }}
